CREATE TABLE IF NOT EXISTS Tarea (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(50) NOT NULL,
  assignedTo VARCHAR(100) NOT NULL,
  dueDate DATETIME NOT NULL
);