services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tareas
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: api_tareas
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy   # ← espera a que MySQL esté listo de verdad
      redis:
        condition: service_healthy
    env_file:
      - .env
    # ← Sin volúmenes: usa lo que está dentro del contenedor

  worker:
    build: .
    container_name: worker_tareas
    command: ["npm", "run", "worker"]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    # ← Sin volúmenes

volumes:
  mysql_data: